mappings:
  Commenting: SilverStripe\Comments\Commenting
  CommentAdmin: SilverStripe\Comments\Admin\CommentAdmin
  CommentsGridField: SilverStripe\Comments\Admin\CommentsGridField
  CommentsGridFieldAction: SilverStripe\Comments\Admin\CommentsGridFieldAction
  CommentsGridFieldBulkAction: SilverStripe\Comments\Admin\CommentsGridFieldBulkAction
  CommentsGridFieldBulkAction_Handlers: SilverStripe\Comments\Admin\CommentsGridFieldBulkAction\Handlers
  CommentsGridFieldConfig: SilverStripe\Comments\Admin\CommentsGridFieldConfig
  CommentingController: SilverStripe\Comments\Controllers\CommentingController
  CommentsExtension: SilverStripe\Comments\Extensions\CommentsExtension
  Comment: SilverStripe\Comments\Model\Comment
  Comment_SecurityToken: SilverStripe\Comments\Model\Comment\SecurityToken
  CommentAdminTest: SilverStripe\Comments\Tests\CommentAdminTest
  CommentingControllerTest: SilverStripe\Comments\Tests\CommentingControllerTest
  CommentingTest: SilverStripe\Comments\Tests\CommentingTest
  CommentListTest: SilverStripe\Comments\Tests\CommentListTest
  CommentsExtensionTest: SilverStripe\Comments\Tests\CommentsExtensionTest
  CommentsGridFieldActionTest: SilverStripe\Comments\Tests\CommentsGridFieldActionTest
  CommentsGridFieldBulkActionTest: SilverStripe\Comments\Tests\CommentsGridFieldBulkActionTest
  CommentsGridFieldConfigTest: SilverStripe\Comments\Tests\CommentsGridFieldConfigTest
  CommentsGridFieldTest: SilverStripe\Comments\Tests\CommentsGridFieldTest
  CommentsTest: SilverStripe\Comments\Tests\CommentsTest
  CommentableItem: SilverStripe\Comments\Tests\Stubs\CommentableItem
  CommentableItemEnabled: SilverStripe\Comments\Tests\Stubs\CommentableItemEnabled
  CommentableItemDisabled: SilverStripe\Comments\Tests\Stubs\CommentableItemDisabled
  CommentableItem_Controller: SilverStripe\Comments\Tests\Stubs\CommentableItemController
  CommentTestHelper: SilverStripe\Comments\Tests\CommentTestHelper
